version: 2.1

jobs:
  test:
    docker:
      - image: cimg/go:1.26
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
            - go-mod-v1-
      - run:
          name: Download Go modules
          command: go mod download
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod
      - run:
          name: Run tests
          command: go test -race -timeout 20m ./...

workflows:
  test:
    jobs:
      - test
